baselines-320
baseline320: spec
  "This groups all baseline"

  <version: '3.2.0-baseline'>

  self baseline320common: spec.
  self baseline311gemstone: spec.
  self baseline312pharo: spec.
  self baseline312slime: spec.
  self baseline320filesystem: spec.
  self baseline311adaptors: spec.
  self baseline311comet: spec.
  self baseline311javascript: spec.
  self baseline311jquery: spec.
  self baseline311jqueryui: spec.
  self baseline311rss: spec.
  self baseline311rest: spec.
  self baseline311scriptaculous: spec.
  self baseline311json: spec.
  self baseline311ob: spec.
  self baseline320gettext: spec.
  self baseline311welcome: spec.
  self baseline320security: spec