baselines-3101
baseline3101: spec
	<version: '3.1.0.1-baseline'>
	"This groups all baseline"
	self baseline3101common: spec.
	self baseline3101gemstone: spec.
	self baseline3101pharo: spec.
	self baseline3101filesystem: spec.
	self baseline3101adaptors: spec.
	self baseline3101comet: spec.
	self baseline3101javascript: spec.
	self baseline3101jquery: spec.
	self baseline3101jqueryui: spec.
	self baseline3101rss: spec.
	self baseline3101rest: spec.
	self baseline3101scriptaculous: spec.
	self baseline3101json: spec.
	self baseline3101ob: spec.
	self baseline3101gettext: spec.
	self baseline3101welcome: spec.