as yet unclassified
baseline310: spec
  "This groups all baseline"

  <baseline>
  self baseline310common: spec.
  self baseline310gemstone: spec.
  self baseline310pharo: spec.
  self baseline310filesystem: spec.
  self baseline310adaptors: spec.
  self baseline310comet: spec.
  self baseline310javascript: spec.
  self baseline310jquery: spec.
  self baseline310jqueryui: spec.
  self baseline310rss: spec.
  self baseline310scriptaculous: spec.
  self baseline310json: spec.
  self baseline310ob: spec.
  self baseline310welcome: spec