options-generated
at: aString
	"Defines which position on ''the target element'' to align the positioned element against: 'horizontal vertical' alignment. A single value such as 'right' will default to 'right center', 'top' will default to 'center top' (following CSS convention). Acceptable values: 'top', 'center', 'bottom', 'left', 'right'. Example: 'left top' or 'center center'"

	self optionAt: 'at' put: aString