options-generated
my: aString
	"Defines which position on ''the element being positioned'' to align with the target element: 'horizontal vertical' alignment. A single value such as 'right' will default to 'right center', 'top' will default to 'center top' (following CSS convention). Acceptable values: 'top', 'center', 'bottom', 'left', 'right'. Example: 'left top' or 'center center'"

	self optionAt: 'my' put: aString